### ISSUE TITLE
We have to improve website a little bit more robust

### ISSUE THREAD

**Issue by ArshErgon** [hannobraun/www.fornjot.app#156]
Hey @hannobraun, I was thinking to improve https://www.fornjot.app/ a little bit more robust, at now website is quite static and simple.

**Comment by hannobraun** [comment]
What do you have in mind?

**Comment by ArshErgon** [comment]
something like https://getstation.com/ and I will be soon be sharing custom design also.

**Comment by hannobraun** [comment]
That website certainly looks better than ours :smile: 

I'm looking forward to see what you come up with!

**Comment by hannobraun** [comment]
Thank you for that design, @ArshErgon! Certainly looks more attractive!

I think I'll need some time to put my thoughts together, and right now I'm busy with some other work. I'll get back to you, probably tomorrow!

**Comment by hannobraun** [comment]
I've had some time to put my thoughts together now. Thank you for your patience, @ArshErgon!

I'll be talking about the general direction of the design, and less so about the details of that mock-up. Those can come later. I think there are two broad areas that need to be discussed:

1. How it looks.
2. What it's supposed to do.

Regarding how it looks, I think this design is definitely prettier than what we currently have. However, it's kind of hard to judge how usable it is going to be without seeing the same design applied to more text-heavy pages. For example [a blog post](https://www.fornjot.app/blog/weekly-release/2022-w50/) or [the Funding page](https://www.fornjot.app/funding/).

The second, and in my opinion more difficult area, is the purpose of the new design. What is the page supposed to do? If we don't know that, we have no way to judge whether a given design is good or not. Looking at your current mock-up, what things would we expect the user to do? Where do we want them to go?

Taking the current home page as an example, I would say it tries to do the following things:

1. Grab some attention by showing a screenshot.
2. Then give an overview of what Fornjot is about.
3. Provide links to more resources, for those interested in learning more.
4. Show the list of sponsors, to give credit and encourage people to become sponsors themselves.
5. Get people to sign up to the newsletter.

I think it does *some* of those things somewhat effectively, namely informing people about Fornjot and funneling them into the newsletter. It could certainly be better, but I don't think that's the problem here. I think the problem here is the list of things it tries to do. There is no clear priority, and users are being pulled in different directions.

And the problem doesn't end there. To even define a priority, we need to know what bigger context that page exists in. Where do visitors come from? Where do we want them to go, and why? Basically, what's missing is a clear marketing strategy.

This is something I've been thinking about in the background for a long time, and it's a hard problem (at least for me). It's made harder because Fornjot is in a preview state at the moment, and is not useful for real work yet.

---

I totally understand that defining a marketing strategy for Fornjot is probably not what you're trying to do here, and I certainly don't expect you to :smile: 

But I think, if we want to create a new design that goes beyond just changing the font and the color scheme (and the current mock-up does go way beyond that), we need to answer at least some of those questions.

**Comment by ArshErgon** [comment]
@hannobraun  The design I have created will be useful for a one-page website, but if we push something on it which is daily updating then we have to choose a framework to handle the heavy work with a better database.

And what's the purpose of creating a new website? everything you have stated is correct.

my main motive is to make Fornjot more public, at now only you are the person who's handling the project alone, I came to know about Fornjot only because at that time I was starting with open source and your issue was `good-first-issue` there are many people who want to work on a tech startup which is on its starting phase.
but only the website is not enough, a well-documented tutorials, a subreddit for Fornjot and an official youtube channel is required for Fornjot, and remember you said why do we need a better website? We have to tell people what in the world is Fornjot? Why do we need it? Why its created in the first place? How's it different from another CAD program

**Comment by ArshErgon** [comment]
Hi @hannobraun well, yeah I think this isn't the right to update the website but in future we will be needing more active contributors and a nice way to show Fornjot.
Sometimes we actually need a database many times some framework don't work properly with the existing DB, and yeah I agree on this that static website is good but users are giving up on static websites, they want a more dynamic website which grabs their attention.
at present time I will try to share Fornjot on socials

**Comment by hannobraun** [comment]
Is it possible that we're talking about two different things?

The current website is static in every sense of the word: The backend just serves static HTML, and there's no JavaScript being executed in the browser. If we wanted a dynamic backend, we'd need a database, but I see no reason for that. If we want to make the website more dynamic in the browser, by including videos, or a Fornjot widget that shows off a model (once that is possible), we don't need a different backend, and no database.

Is that it, or am I missing something?


> at present time I will try to share Fornjot on socials

That sounds great!

**Comment by ArshErgon** [comment]
You have more experience than me in tech, you understand things much faster and better than me.
A quick google search:
> "when should we migrate from a database to another": In general, there are various reasons to migrate from one database to another which include performance issues, stability, reliability, High Availability issues, costs for the license (dual license, GPL), etc

We can get a dynamic website without upgrading the database or using another framework, my plan was to make only the front page(the Figma file)  and then later as the number of clicks increases add more pages to it

**Comment by ArshErgon** [comment]
Wait, so you mean all your blogs and images aren't saved inside a database? You are serving it statically? Now I'm feeling quite stupid.🥲🥲 Godd I'm really sorry

Okay, so I think this issue is not required right now.

**Comment by hannobraun** [comment]
Exactly! They are stored in this repository (for example, [all data for the latest progress report](https://github.com/hannobraun/www.fornjot.app/tree/main/content/blog/progress-report-2022-11)) and get converted into static HTML when the website is deployed.

**Comment by hannobraun** [comment]
Closing, as this issue tracks no actionable work. We can open more focused issues, as we think of specific improvements.
